#!/bin/sh

### Setup
origin="${ORIGIN:-origin}"

### Delete merged branches
merged_branches=$(git branch -r --merged | cat | sed "s/  origin\///g")

while IFS= read -r branch; do
    merged_branches=$(echo "$merged_branches" | grep -v "$branch")
done < whitelist

if [ -n "$merged_branches" ]; then
    tmp="$(mktemp)"
    echo "$merged_branches" > "$tmp"
    while IFS= read -r branch; do
        echo "Deleting branch $branch..."
        if [ -z "$DRY_RUN" ]; then
            git push "$origin" --delete "$branch"
        fi
    done < "$tmp"
    rm "$tmp"
else
    echo "No merged branches to delete!"
fi
